### ISSUE TITLE
[blocker] No prerendering with 1.4.0

### ISSUE THREAD

**Issue by KenjiBaheux** [toyoshim/Prerender-Tweaks#1]
No sure what's going on but with the latest version, I don't see any blue P indicator, nor any blue bars in the histograms.
This suggests that there is no prerendering happening or that the stats/indicators are broken.

Chrome stable 110.0.5481.177 on a macbook.

**Comment by toyoshim** [comment]
Specific site lists that the Extension doesn't work well.
- https://www.vox.com/technology
