### ISSUE TITLE
[blocker] Show time saved at navigation time

### ISSUE THREAD

**Issue by KenjiBaheux** [toyoshim/Prerender-Tweaks#2]
Most users won't dig into the stats on a regular basis and may not appreciate the value provided by prerendering.

Instead of showing a blue P, I think it would be more interesting to show a (green) badge with the amount of time that was saved for a page load that benefited from prerender:
 - Something like the time between the start of prerendering and the min of (LCP, navigation time)

IIRC, the badge (noted as [      ]) can have 4 characters, which could be used as follows:
 - [0.1s] for small wins (e.g. less than 150ms) to avoid showing a 0.0s "win". Perhaps, rounding up all the wins to the next hundred ms would be quick and reasonable.
 - [0.5s] for a 500 ms win 
 - [1.7s] for 1700 ms win
 - [10+s] for more than 9999 ms win (should be really rare)

**Comment by toyoshim** [comment]
confirmed that [0.1s] can fit the badge view width. Or `↑0.1s` may be better?

**Comment by toyoshim** [comment]
Implemented in 1.4.3
