### ISSUE TITLE
[P2] Can we show an [X] red badge on sites that are not allowed?

### ISSUE THREAD

**Issue by KenjiBaheux** [toyoshim/Prerender-Tweaks#3]
For sites where the extension is disallowed (e.g. internal / incompatible sites), it would be useful to show the [x] red badge to indicate that the extension is unable to deliver anything.

P2 / Nice to have.

**Comment by toyoshim** [comment]
As content scripts are silently banned in the case the enterprise policy disallows it, I cannot find a good way to detect the case.
