### ISSUE TITLE
[blocker-ish] per-site master switch

### ISSUE THREAD

**Issue by KenjiBaheux** [toyoshim/Prerender-Tweaks#4]
In case the extension breaks something or causes unexpected side-effects/surprises, I think it would be good to have a master on/off switch for each site. 

Perhaps, an "Enable on this site" toggle that defaults to enable unless the user is on unsupported / disallowed pages (e.g. NTP, internal sites, blocked by the user).

Either a blocker or something that we might need to quickly follow-up with to release an updated version asap in case something goes bad.

**Comment by toyoshim** [comment]
implemented in 1.4.2
