### ISSUE TITLE
[blocker-ish] Pinning

### ISSUE THREAD

**Issue by KenjiBaheux** [toyoshim/Prerender-Tweaks#5]
Is it possible to have the extension pinned by default? Some permission perhaps?
Or, some guidance when the extension is installed to encourage our users to pin the extension?

If we can't do much, then we can do some high touch guidance for key folks.

**Comment by toyoshim** [comment]
It's completely up to users, and there is no such permission or something to enforce it by default.

> Users can choose to pin your extension icon to the toolbar.
https://developer.chrome.com/docs/extensions/reference/action/

Or enterprise policy can do it.
https://support.google.com/chrome/a/answer/11190170?hl=en
