### ISSUE TITLE
Consider a prettier icon

### ISSUE THREAD

**Issue by domenic** [toyoshim/Prerender-Tweaks#8]
(Low-priority; only do this if you enjoy it)

Consider making a prettier icon, probably by using an AI image generator. https://www.google.com/search?q=generate+an+icon+for+your+app+using+ai has some good results.

**Comment by toyoshim** [comment]
I asked my stable diffusion to create one.
They are good at drawing fine-grained pictures, but it wasn't the best for simplified icons. Maybe there is a prompt engineering to ask for better icons. Anyway I checked in the one.
